//
//  find_downstream_struct.c
//  
//
//  Created by Eric Strobel on 8/25/26.
//

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../../global/global_defs.h"
#include "../../global/global_structs.h"

#include "../../utils/io_management.h"
#include "../../seq_utils/mk_fasta.h"

#include "../filter_by_characteristics_defs.h"
#include "../filter_by_characteristics_structs.h"

#include "./parse_descriptor_file.h"
#include "./get_msa_subseq.h"
#include "./run_RNAStructure.h"
#include "./parse_ct_file.h"
#include "./set_attributes.h"

#include "find_downstream_struct.h"

//NOTE: need control on whether this is run - don't need to run extra predictions if assessing full sequence, prob not necessary with reactivity constraints either
//NOTE: currently only works for proximal deltaG predictions
/* find_downstream_struct: perform iterative structure predictions to identify structures downstream of an initial structure */
int find_downstream_struct(structProps * sp, descriptor * des, sequence_attributes * sq_att, char * path2RNAStructure, char * nm, char * path2ct, int ct_path_maxlen, int ptyp, int ext_limit)
{
    extern char path2fold[MAX_LINE+1];
    extern char tmp_fasta_path[11];
    extern char ct_output_path[11];
    extern char fa_sffx[4];
           
    int verbose = 0;
    
    char full[MAX_LINE+1] = {0};    //longest sequence used for structure prediction
    char * tmp = NULL;              //pointer for allocating memory to store strings used for prediction
    char tmp_nm[MAX_LINE+1] = {0};  //name used for generating fasta and ct files
    int ret = 0;                    //snprintf return value
    
    int ct_cnt[MAX_EXT_LIMIT] = {0}; //number of connectivity tables generated by a prediction
    
    char command[MAX_LINE+1] = {0}; //array for generating system commands
    
    int i = 0; //general purpose index
    int j = 0; //general purpose index
    int x = 1; //extension length of current prediction
    int c = 0; //index/count of kept connectivity tables
        
    con_table * ds_ct = NULL;        //pointer for allocating connectivity table structures
    con_table ** ds_ct2keep = NULL;  //ptr to ptr for cts that will be kept. handles multiple prediction cases
    con_table * crnt_ds_ct = NULL;   //current downstream connectivity table
    con_table * lwst_dG_ct = NULL;   //lowest deltaG connectivity table
    
    con_table * tmp_p_ct = NULL;     //temp pointer to connectivity table
    
    int fnd_substr = 0; //flag that prev dot-bracket is substructure of current dot-bracket
    int tested_all = 0; //flag that all connectivity tables were tested
    
    //allocate memory for storing connectivity tables
    if ((ds_ct = calloc(ext_limit, sizeof(*ds_ct))) == NULL) {
        printf("find_downstream_struct: error - failed to allocate connectivity table memory. aborting...\n");
        abort();
    }
    
    if ((ds_ct2keep = calloc(ext_limit, sizeof(*ds_ct2keep))) == NULL) {
        printf("find_downstream_struct: error - failed to allocate connectivity table memory. aborting...\n");
        abort();
    }
        
    char prev_db[MAX_LINE+1] = {0}; //previous dot-bracket secondary structure
    char * p_dbss = NULL;           //pointer to dot-bracket substring
    
    int len = 0; //string length
    
    int xtndd_orig = 0; //flag that original structure was extended
    
    char pre_nt[MAX_EXT_LIMIT+1] = {0}; //array for storing preceeding nucleotide characters
    char nxt_nt[MAX_EXT_LIMIT+1] = {0}; //array for storing next nucleotide characters
    
    //get longest sequene to be used for prediction
    get_msa_subseq(&tmp, sq_att->sq0, des->wndw[0].b1, des->wndw[0].b2 + ext_limit, BOUND2_INDEX, NULL, NULL, 0, 0);
    strcpy(full, tmp);                     //store fully extended prediction sequence
    
    if (verbose) {
        printf("    \t     \t%s\n", full);           //print fully extended prediction sequence
        printf("    \t%5.1f\t%s\n", sp->dG, sp->db); //printing only one structure
    }
    
    //starting at an extension of 1 nt, perform structure predictions up to an extension length of ext_limit
    //predicted structures that extend the previous structure by an unpaired nucleotide are ignored.
    //predicted structures that extend the original structure and have a lower predicted deltaG are used
    //to set the 'ext_dG' value in sp
    
    for (i = 0, x = 1, c = 0, xtndd_orig = 0, strcpy(prev_db, sp->db); i < ext_limit; i++, x++) {
        //generate a name to be used for structure prediction
        ret = snprintf(tmp_nm, MAX_LINE, "%s_plus%d", nm, x);
        if (ret >= MAX_LINE || ret < 0) {
            printf("find_downstream_struct: error - error when constructing output file name. aborting...\n");
            abort();
        }
        
        //get extended subseq and generate fasta file
        get_msa_subseq(&tmp, sq_att->sq0, des->wndw[0].b1, des->wndw[0].b2 + x, BOUND2_INDEX, &pre_nt[c], &nxt_nt[c], 1, 1);
        mk_fasta_file(tmp_nm, tmp, tmp_fasta_path);
        
        //perform structure prediction using RNAStructure Fold algorithm
        run_RNAStructure_Fold(path2RNAStructure, tmp_nm, tmp_fasta_path, ct_output_path, fa_sffx, path2ct, MAX_LINE, des->act.ptyp);
        ct_cnt[c] = parse_ct_file(&ds_ct[c], path2ct, tmp_nm); //parse connectivity table and set ct_cnt
        
        
        //print predicted dot-bracket structures
        for (j = 0, tmp_p_ct = &ds_ct[c]; j < ct_cnt[c]; j++) {
            if (verbose) {
                printf("%s%d\t%5.1f\t%s\n", (ct_cnt[c] > 1) ? "mul" : "sgl", j+1, tmp_p_ct->dG, tmp_p_ct->db);
            }
            
            if (tmp_p_ct->nxt != NULL) {
                tmp_p_ct = tmp_p_ct->nxt;
            }
        }
        
        
        if (ct_cnt[c] > 1) { //if there was more than one predicted structure
            
            //initialize variables
            p_dbss = NULL;
            fnd_substr = 0;
            tested_all = 0;
            crnt_ds_ct = &ds_ct[c];
            lwst_dG_ct = &ds_ct[c];
            
            //for all predicted structures, test whether the previous structure
            //is a substring of any of the current predicted structures
            while (!fnd_substr && !tested_all) {
                
                if (crnt_ds_ct->dG < lwst_dG_ct->dG) { //if the current structure delta G is less than the lowest dG
                    lwst_dG_ct = crnt_ds_ct;           //point lwst_dG_ct to the current structure
                }
                
                if ((p_dbss = strstr(crnt_ds_ct->db, prev_db)) != NULL) { //search for prev_db in current dot-bracket
                    
                    //if prev_db is a substructure of current db
                    if ((uint64_t)(p_dbss) == (uint64_t)(crnt_ds_ct->db) && crnt_ds_ct->db[strlen(prev_db)] == '.') {
                        fnd_substr = 1; //set flag that substring was found
                    }
                    
                } else if (crnt_ds_ct->nxt != NULL) { //if other structures were predicted
                    crnt_ds_ct = crnt_ds_ct->nxt;     //point crnt_ds_ct to the next structure
                    
                } else {            //otherwise,
                    tested_all = 1; //set flag that all predicted structures were tested
                }
            }
            
            if (!fnd_substr) {           //if the previous structure is not a substructure of any current structures
                crnt_ds_ct = lwst_dG_ct; //keep the lowest delta G structure
            }
            
        } else { //if there was only one predicted structure
            crnt_ds_ct = &ds_ct[c];                   //point crnt_ds_ct to the current downstream connectivity table
            p_dbss = strstr(crnt_ds_ct->db, prev_db); //search for prev_db in current dot-bracket
        }        
        
        //if current dot-bracket structure only extends the previous dot-bracket structure by an unpaired nucleotide,
        //store the deltaG value of the current prediction, extend prev_db by a single '.' char, and free ct memory
        //in this way, predictions that are effectively identical to previous predictions are ignored and only
        //prediction in which the structure meaningfully changes are kept. The purpose of storing the delta G of the
        //current prediction is because, in some cases, extension of a structure by an unpaired nucleotide lowers the
        //predicted delta G. When this occurs for the original structure prediction (sp), the delta G of the extended
        //structure is stored as 'ext_dG' in sp.
        
        if ((uint64_t)(p_dbss) == (uint64_t)(crnt_ds_ct->db) && crnt_ds_ct->db[strlen(prev_db)] == '.') {

            //current prediction extends the previous prediction by one unpaired nucleotide
            
            len = strlen(prev_db);                  //set the length of the previous prediction
            prev_db[len]   = '.';                   //add a '.' char to the previous prediction
            prev_db[len+1] = '\0';                  //terminate the previous prediction string
            
            free_con_table_mem(&ds_ct[c], ct_cnt[c]);  //free the current prediction's connectivity table
            
        } else { //current prediction is distinct from the previous prediction
            
            ds_ct2keep[c] = crnt_ds_ct;
            
            strcpy(prev_db, crnt_ds_ct->db); //store current dot-bracket structure for comparison to next prediction
            c++;                             //increment connectivity table index
        }
        
        free(tmp); //free temporary sequence storage
    }
    
    if (c) {
        if ((sp->ds = calloc(c, sizeof(*(sp->ds)))) == NULL) {
            printf("find_downstream_struct: error - failed to allocate extended structProps memory. aborting...\n");
            abort();
        }
        
        if (verbose) {
            printf("\nc = %d\n", c);
            printf("     \t%s\n", full);
            printf("%5.1f = ext_dG\n", sp->ext_dG);
            printf("%5.1f\t%s\n", sp->dG, sp->db);
        }
        
        for (i = 0; i < c; i++) {
            if ((sp->ds[i] = calloc(c, sizeof(*(sp->ds[i])))) == NULL) {
                printf("find_downstream_struct: error - failed to allocate extended structProps memory. aborting...\n");
                abort();
            }
            set_structProps(sq_att, pre_nt[c], nxt_nt[c], NULL, TYPE_INIT, ds_ct2keep[i]->bs, sp->ds[i], ds_ct2keep[i], 1, des, path2RNAStructure);  //set structProps values
            if (verbose) {
                printf("%5.1f\t%s\n", ds_ct2keep[i]->dG, ds_ct2keep[i]->db);
            }
        }
        if (verbose) {
            printf("\n");
        }
    }
    
    for (i = 0; i < c; i++) {
        free_con_table_mem(ds_ct2keep[i], ct_cnt[i]);
    }
    
    free(ds_ct);
    free(ds_ct2keep);
    
    return i;
}

/* mv_ct_to_LL_top: move a con_table struct to the top of the con_table linked list (not currently using this) */
void mv_ct_to_LL_top(con_table * new_top, con_table * old_top)
{
    //printf("in mv_ct_TO_LL_top: ");
    
    con_table * old_top_nxt = old_top->nxt;
    con_table * new_top_prv = new_top->prv;
    con_table * new_top_nxt = new_top->nxt;
    
    if ((uint64_t)(new_top) == (uint64_t)(old_top)) { //new_top is already at the top
        //printf("new_top is already at the top\n");
        return;
        
    } else if ((uint64_t)(old_top_nxt) == (uint64_t)(new_top) && //new_top is next LL element after old_top
               (uint64_t)(new_top_prv) == (uint64_t)(old_top)) {
        
        printf("new_top is next LL element after old_top\n");
        
        new_top->prv = NULL;
        new_top->nxt = old_top_nxt;
        old_top->prv = new_top_prv;
        old_top->nxt = new_top_nxt;
        
    } else if ((uint64_t)(old_top_nxt) != (uint64_t)(new_top) && //new_top and old_top are separated
               (uint64_t)(new_top_prv) != (uint64_t)(old_top)) {
        
        printf("new_top and old_top are separated\n");
        
        new_top->prv = NULL;
        new_top->nxt = old_top;
        old_top->prv = new_top;
        
        new_top_prv->nxt = new_top_nxt;
        if (new_top_nxt != NULL) {          //if there is another LL element after new_top
            new_top_nxt->prv = new_top_prv;
        }
    } else {
        printf("mv_ct_to_LL_top: error - it should not be possible to get here. aborting...\n");
        abort();
    }
    
    return;
}
